FROM python:3

# WARNING: Do not use this Dockerfile for production installs. It creates a
# temporary database that is stored in the container, which you definitely
# don't want for production.

RUN apt-get update \
        && apt-get install -y \
            git \
            libcap-dev \
            libjansson-dev \
            libpcre3-dev \
            librsvg2-bin \
            libsasl2-dev \
            libyaml-dev \
            optipng \
            uuid-dev \
        && pip install --no-cache-dir pip-tools

RUN pip install --no-cache-dir uWSGI==2.0.17

WORKDIR /usr/src/app

# install python dependencies
COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /usr/src/app

ENV PYTHONPATH /usr/src/app
ENV FLASK_APP wuvt
ENV USE_EMBEDDED_DB 1

RUN python setup.py render_svgs

# set permissions and create media directory
RUN chown www-data:www-data wuvt . && \
        install -d -o www-data -g www-data /data/media

EXPOSE 8080
ENTRYPOINT ["/usr/src/app/entrypoint-dev.sh"]
CMD ["uwsgi" , "--ini", "uwsgi_docker.ini:dev"]
