"""add orders table

Revision ID: 187cf9175cee
Revises: 3d8cf74c2de4
Create Date: 2015-10-23 23:43:31.769594

"""

# revision identifiers, used by Alembic.
revision = '187cf9175cee'
down_revision = '3d8cf74c2de4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('email', sa.Unicode(length=255), nullable=True),
    sa.Column('phone', sa.Unicode(length=12), nullable=True),
    sa.Column('placed_date', sa.DateTime(), nullable=True),
    sa.Column('dj', sa.UnicodeText(), nullable=True),
    sa.Column('thank_on_air', sa.Boolean(), nullable=True),
    sa.Column('first_time', sa.Boolean(), nullable=True),
    sa.Column('premiums', sa.Unicode(length=255), nullable=True),
    sa.Column('address1', sa.Unicode(length=255), nullable=True),
    sa.Column('address2', sa.Unicode(length=255), nullable=True),
    sa.Column('city', sa.Unicode(length=255), nullable=True),
    sa.Column('state', sa.Unicode(length=255), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('shipped_date', sa.DateTime(), nullable=True),
    sa.Column('tshirtsize', sa.Unicode(length=255), nullable=True),
    sa.Column('tshirtcolor', sa.Unicode(length=255), nullable=True),
    sa.Column('sweatshirtsize', sa.Unicode(length=255), nullable=True),
    sa.Column('method', sa.Unicode(length=255), nullable=True),
    sa.Column('custid', sa.Unicode(length=255), nullable=True),
    sa.Column('comments', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    ### end Alembic commands ###
