"""add index on Track.artist

Revision ID: 52899175817
Revises: d5174540a4d
Create Date: 2015-12-02 00:48:26.156154

"""

# revision identifiers, used by Alembic.
revision = '52899175817'
down_revision = 'd5174540a4d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('page', 'content',
               existing_type=mysql.LONGTEXT(),
               nullable=False)
    op.create_index(op.f('ix_track_artist'), 'track', ['artist'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_artist'), table_name='track')
    op.alter_column('page', 'content',
               existing_type=mysql.LONGTEXT(),
               nullable=True)
    ### end Alembic commands ###
